all: imagenet_parser

imagenet_parser: imagenet_parser.cpp
	# g++ -O2 -std=c++11 imagenet_parser.cpp -o imagenet_parser -lopencv_core -lopencv_imgcodecs -lopencv_imgproc -lopencv_highgui
	g++ -O2 -std=c++11 imagenet_parser.cpp -o imagenet_parser
